[tool.poetry]
name = "hw-27"
version = "1.4.0"
description = ""
authors = ["Nikita"]
readme = "README.md"
packages = [{include = "hw_27"}]

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.1.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
